### ISSUE TITLE
Introduce nightly build for incremental but full recipe coverage

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#2168]
This is to discuss a feature to implement in order to have a full recipe coverage build time.
The idea is to compile every nights a subset of our recipes.
```
name: Nightly build
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  nightly:
    name: Nightly build
    ...
```
This covers builds time checks first and may cover runtime checks in the future.
